
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fuat
 */
public class YHB extends javax.swing.JFrame {

    /**
     * Creates new form ww
     */
    public YHB() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btndon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fuat\\Desktop\\ملفات java\\صور مشروع 77\\ev (2).png")); // NOI18N
        jLabel1.setText("ى نحو ممتاز مع برامج سطح المكتب مثل Microsoft Outlook وApple Mail وMozilla Thunderbird. ويمكن لمستخدمي Outlook مزامنة رسائل البريد الإلكتروني والأحداث وجهات الاتصال من وإلى Google Workspace.\n\nنقل البيانات بسهولة من Outlook والخدمات القديمة\nيمكنك نقل بيانات بريدك الإلكتروني من Outlook أو Exchange أو Lotus بسهولة باستخدام أدوات مخصّصة تساعدك على الاحتفاظ برسائلك المهمة.\n\nضمان وقت التشغيل بنسبة 99.9% ووقت توقف مُخطّط بنسبة 0%\nيمكنك الاعتماد على البنية التحتية العالمية لشركة Google التي تتسم بالأمان والمرونة، لضمان استمرارية العمل على مدار الساعة طوال أيام الأسبوع طيلة العام. وتساعدك عمليات النسخ الاحتياطي التلقائي والحماية من الرسائل غير المرغوب فيها، علاوة على معايير الأمان الرائدة في هذا المجال على حماية بيانات نشاطك التجاري.");

        btndon.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btndon.setForeground(new java.awt.Color(0, 0, 51));
        btndon.setIcon(new javax.swing.ImageIcon("C:\\Users\\fuat\\Desktop\\ملفات java\\صور مشروع 77\\back.png")); // NOI18N
        btndon.setText("Geri Dön");
        btndon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonActionPerformed(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTextPane1.setText("DOĞAN ERKEK ÖĞRENCİ YURDU:\nAdres: İsmet Paşa Mahallesi,36012 Sokak, No:20, 46100 Kahramanmaraş Merkez/ Kahramanmaraş,Türkiye\nKaç Yıldır Hizmet Veriyor:  2012 den beğri hizmete açıktır.\nÇalışan Sayısı: 5\nÇalışan İsimleri ve Görevleri: \nYasin DOĞAN = Yurt Müdürü\nMehmet ALSANCAK =Aşçı\nSelim AKTAN = Güvenlik Görevlisi\nBerk KÜÇÜK = Temizlikçi\nMert KAHVECİ= Yurt Müdür Yardımcısı\nDoğan Erkek Öğrenci Yurdu Özellikleri:\nGeniş tek ve çift kişilik odalar…\nKişiye özel banyo-tuvalet imkanı…\n100 metre mesafede otobüs durakları…\nKahramanmaraş Sütçü İmamÜniversitesine 15 dakikada ulaşım imkanı…\nYurdumuzda elektrik, internet, ısınma, ve sabah kahvaltısı hizmetleri ücret talep edilmeden verilmektedir.\nÇamaşır yıkama hizmeti vermekteyiz.\nBinamızda duvarlar 26 santimetre kalınlığında olup ısı ve ses yalıtımlıdır.\nYurt Kuralları:\n1-Kavga edenler yurttan atılır.\n2-Sigara ve alkol almak yasak.\n3-Sabah kahvaltı saati 07.00-08.30.\n4-Akşam yemeği saat 18.00-20.00.\n5-Gece 23.00 dan sonra içeriye alım olmayacktır");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndon)
                .addGap(363, 363, 363))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btndon)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonActionPerformed
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btndonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
                        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YHB().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
